[project]
authors = ["IMJONEZZ <chrisbrousseau304@gmail.com>"]
channels = ["conda-forge", "https://prefix.dev/conda-forge", "nvidia", "pytorch", "xformers"]
name = "3dspherefrom2dimg"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.4"

[dependencies]
python = "3.11.9*"
cuda-version = "==12.4"

[pypi-dependencies]
numpy = ">=2.2.5, <3"
matplotlib = ">=3.10.3, <4"
scikit-image = ">=0.25.2, <0.26"
scipy = ">=1.15.3, <2"
tqdm = ">=4.67.1, <5"
torch = { version = "==2.5.1", index = "https://download.pytorch.org/whl/cu124"}
torchvision = { version = "==0.20.1", index = "https://download.pytorch.org/whl/cu124"}
opencv-python = ">=4.11.0.86, <5"
